name: hello

on:
  push:
    branches: [hello]
  pull_request:
    branches: [hello]
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello from Github Actions!"